### ISSUE TITLE
Supported versions

### ISSUE THREAD

**Issue by ehsandotnet** [alaasalman/ussdinterceptor#1]
which android versions does it support?

**Comment by ghost** [comment]
It supports only the earlier versions of Android, until 4.2 (i think)

**Comment by alaasalman** [comment]
That's correct.

**Comment by pligor** [comment]
Based on this line:
_“The rights of root are necessary for the program for processing of USSD answers to Android 4.2.2 above_ - https://play.google.com/store/apps/details?id=com.mdnsoft.ussddualwidgetpro

and this line: _It wont work with 4.2.2 due to security restrictions(changes have been made to PhoneApp code)_ - http://stackoverflow.com/questions/5477597/how-is-it-possible-to-do-ussd-requests-on-android

4.2.2 and after are not supporting apps which can handle USSDs

Is there any way to circumvent that? Any hackerish way would be acceptable.
Because an app can get very useful information from USSDs

Thank you
